---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/platform-engineering-showcase/refs/heads/main/taskfiles/git.yaml

vars:
  PROJECT_NAME:
    sh: echo ${PWD##*/}
  BRANCH:
    sh: if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then echo $(git rev-parse --abbrev-ref HEAD); else echo main ; fi
  ORGA_NAME: stuttgart-things
  MODULE: github.com/{{ .ORGA_NAME }}/{{ .PROJECT_NAME }}
  CI_MODULE: .dagger
  DATE:
    sh: date -Ih

tasks:
  test-all:
    cmds:
      - |
        dagger call -m {{ .CI_MODULE }} run-all-tests-with-report \
        --source . \
        export --path={{ .REPORT_PATH }}
        cat {{ .REPORT_PATH }}
    vars:
      REPORT_PATH: /tmp/{{ .PROJECT_NAME }}-test-report.json

  ci-run-static-checks:
    cmds:
      - |
        dagger call -m {{ .CI_MODULE }} {{ .FUNCTION }} \
        --src {{ .SRC }} \
        --lintCanFail=true \
        --go-Version=1.25.4 \
        --test={{ .TEST }} \
        --progress plain -vv \
        export --path={{ .REPORT_PATH }}
        cat {{ .REPORT_PATH }}
    vars:
      SRC: .
      TEST: true
      FUNCTION: run-static-stage
      REPORT_PATH: /tmp/{{ .PROJECT_NAME }}-static-analysis-report.json

  check:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run -a

  release:
    desc: Push new version
    deps: [check, lint, test]
    cmds:
      - task: pr
      - npx semantic-release --dry-run
      - npx semantic-release --debug --no-ci
      - echo released version $(git describe --tags --abbrev=0)

  lint:
    desc: Lint Golang
    cmds:
      - cmd: golangci-lint run
        ignore_error: true

  tag:
    desc: Commit, push & tag the module
    deps: [lint, test, commit]
    cmds:
      - git pull
      - go mod tidy
      - git tag -a {{ .TAG }} -m 'updated for stuttgart-things {{.DATE}} for tag version {{ .TAG }}'
      - git push origin --tags

  default:
    desc: Default task is select & do (work)
    cmds:
      - task do

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"
